config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :vendors
  resources :docks
  resources :workers

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'welcome/home', to: 'welcome#home'
  get 'welcome/manual', to: 'welcome#manual'
  get 'welcome/post_mortem', to: 'welcome#post_mortem'
  get 'welcome/requirements', to: 'welcome#requirements'
  get 'welcome/design_documentation', to: 'welcome#design_documentation'
  get 'welcome/docs_main', to: 'welcome#docs_main'
  get 'welcome/report', to: 'welcome#report'
  post 'welcome/report', to: 'welcome#report'
  get 'welcome/dockreport', to: 'welcome#dockreport'


end

app/models/vendor.rb
class Vendor < ApplicationRecord

has_many :appointments
validates :name, presence: true
validates :name, uniqueness: true
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: [:show, :edit, :update, :destroy]

  # GET /vendors
  # GET /vendors.json
  def index
    @vendor = Vendor.where(:archive => false)
  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show


  end

  def show1
    respond_to do |format|
      format.js  {render layout: false}

    end

  end







  # GET /vendors/new
  def new
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(vendor_params)

    respond_to do |format|
      if @vendor.save

        format.html { redirect_to @vendor, notice: 'Vendor was successfully created.' }
        format.json { render :show, status: :created, location: @vendor }

      else
        format.html { render :new }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendors/1
  # PATCH/PUT /vendors/1.json
  def update
    respond_to do |format|
      if @vendor.update(vendor_params)
        format.html { redirect_to @vendor, notice: 'Vendor was successfully updated.' }
        format.json { render :show, status: :ok, location: @vendor }
      else
        format.html { render :edit }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    #@vendor.destroy

    @vendor = Vendor.find(params[:id])
    @vendor.update_attribute(:archive,  true)


    respond_to do |format|
      format.html { redirect_to vendors_url, notice: 'Vendor was successfully archived.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vendor_params
      params.require(:vendor).permit(:name)
    end
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_form.html.erb
<%= form_for(vendor) do |f| %>
    <% if vendor.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(vendor.errors.count, "error") %> -- Khhhaaaaaaannn! Vendor not saved!</h2>

          <ul>
            <% vendor.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/vendors/_show1.html.erb
<table>
  <h1>Vendor Info</h1>


  <thead>
  <tr>
    <th>Vendor Name</th>
    <th>Vendor ID</th>
    <th>Created date</th>

  </tr>
  </thead>

  <tbody>
  <tr valign="top">
  <td><%= vendor.name %></td>
  <td><%= vendor.id %></td>
   <td><%= vendor.created_at %></td>


  </tr>
        </tbody>
</table>

app/views/vendors/edit.html.erb
<h1>Editing Vendor</h1>

<%= render 'form', vendor: @vendor %>


<%= link_to 'Back', vendors_path ,class: 'btn-back'%>

app/views/vendors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vendors</h1>
<%= link_to 'New Vendor', new_vendor_path, class: "new_btn" %>
<br>
<br>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
</table>
<br>

<div id="scroll">
<table>
  <tbody>
    <% @vendor.each do |vendor| %>
      <tr>
        <td><%= vendor.name %></td>
        <td col width="55"><%= link_to 'Detail', vendor, :remote => true, class: 'btn-index' %></td>
        <td col width="55"><%= link_to 'Edit', edit_vendor_path(vendor), class: 'btn-index' %></td>
        <td><%= link_to 'Archive', vendor, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn-index'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

</div>

<div id="content"></div>

app/views/vendors/new.html.erb
<h1>New Vendor</h1>

<%= render 'form', vendor: @vendor %>

<%= link_to 'Back', vendors_path ,class: 'btn-back'%>

app/views/vendors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vendor.name %>
</p>

<%= link_to 'Edit', edit_vendor_path(@vendor),class: 'btn-back' %> |
<%= link_to 'Back', vendors_path,class: 'btn-back' %>

app/views/vendors/show.js.erb
$("#content").html("<%= escape_javascript(render partial: 'vendors/show1', locals: { vendor: @vendor } ) %>");