config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :vendors
  resources :docks
  resources :workers

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'welcome/home', to: 'welcome#home'
  get 'welcome/manual', to: 'welcome#manual'
  get 'welcome/post_mortem', to: 'welcome#post_mortem'
  get 'welcome/requirements', to: 'welcome#requirements'
  get 'welcome/design_documentation', to: 'welcome#design_documentation'
  get 'welcome/docs_main', to: 'welcome#docs_main'
  get 'welcome/report', to: 'welcome#report'
  post 'welcome/report', to: 'welcome#report'
  get 'welcome/dockreport', to: 'welcome#dockreport'


end

app/models/worker.rb
class Worker < ApplicationRecord

has_many :worker_appointments
  has_many :appointments, :through => :worker_appointments
has_one :dock, :through =>  :appointments

validates :name, presence: true
validates :name, uniqueness: true
validates :address, presence: true
validates :city, presence: true
validates :state, presence: true
validates :zip, presence: true, numericality: true
validates :payrate, presence: true, numericality: true

  accepts_nested_attributes_for :appointments


end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  before_action :set_worker, only: [:show, :edit, :update, :destroy]

  # GET /workers
  # GET /workers.json
  def index
    @worker = Worker.where(:archive => false)

  end

  # GET /workers/1
  # GET /workers/1.json
  def show1
    respond_to do |format|
      format.js  {render layout: false}
    end
  end

  def show

  end









  # GET /workers/new
  def new
    @worker = Worker.new
  end

  # GET /workers/1/edit
  def edit
  end

  # POST /workers
  # POST /workers.json
  def create
    @worker = Worker.new(worker_params)

    respond_to do |format|
      if @worker.save
        format.html { redirect_to @worker, notice: 'Worker was successfully created.' }
        format.json { render :show, status: :created, location: @worker }
      else
        format.html { render :new }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /workers/1
  # PATCH/PUT /workers/1.json
  def update

    @worker = Worker.find(params[:id])


    respond_to do |format|
      if @worker.update(worker_params)
        format.html { redirect_to @worker, notice: 'Worker was successfully updated.' }
        format.json { render :show, status: :ok, location: @worker }
      else
        format.html { render :edit }
        format.json { render json: @worker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /workers/1
  # DELETE /workers/1.json
  def destroy
    #@worker.destroy

    @worker = Worker.find(params[:id])
    @worker.update_attribute(:archive,  true)

    respond_to do |format|
      format.html { redirect_to workers_url, notice: 'Worker was successfully archived.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worker
      @worker = Worker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def worker_params
      params.require(:worker).permit(:name, :address, :city, :state, :zip, :payrate)
    end
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/workers/_form.html.erb
<%= form_for(worker) do |f| %>
  <% if worker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(worker.errors.count, "error") %> -- Khhhaaaaaaannn! Worker not saved!</h2>

      <ul>
      <% worker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.text_field :address %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">

    <%= f.label :state %>
    <%= f.select :state, %w{AL AK AZ AR CA CO CT DC DE FL GA HI ID IL IN IA KS KY LA ME MA MI MN MO MS
MT NE NV NH NJ NM NY NC ND OH OK OR PA RI SC SD TN TX UT VA VT WA WI WV WY} %>
  </div>

  <div class="field">
    <%= f.label :zip %>
    <%= f.text_field :zip %>
  </div>

  <div class="field">
    <%= f.label :payrate %>
    <%= f.text_field :payrate %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/workers/_show1.html.erb
<table>
  <h1>Worker Detail</h1>



  <thead  class="table_head">
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>City</th>
    <th>State</th>
    <th>Zipcode</th>
    <th>Payrate</th>

  </tr>
  </thead>

  <tbody>
  <td><%= worker.name %></td>
  <td><%= worker.address %></td>
  <td><%= worker.city %></td>
  <td><%= worker.state %></td>
  <td><%= worker.zip %></td>
  <td><%= worker.payrate %></td>



  </tbody>
</table>

app/views/workers/edit.html.erb
<h1>Editing Worker</h1>

<%= render 'form', worker: @worker %>


<%= link_to 'Back', workers_path,class: 'btn-back' %>

app/views/workers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Workers</h1>


 <p style="text-align: center"> <%= link_to 'New Worker', new_worker_path, class: "new_btn" %></p>
<br>
<br>

<table>
  <thead class="table_head">

    <tr>

      <th>Name</th>



    </tr>

  </thead>

  </table>
<br>

  <div id="scroll">
    <table>
  <tbody >
    <% @worker.each do |worker| %>
      <tr>
        <td col width="450"><%= worker.name %></td>

        <td col width="55"><%= link_to 'Detail', worker, :remote => true, class: 'btn-index' %></td>
        <td col width="55"><%= link_to 'Edit', edit_worker_path(worker), class: 'btn-index' %></td>
        <td ><%= link_to 'Archive', worker, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn-index' %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>
<br>
<br>
<br>
</div>

<div id="worker_content"></div>

app/views/workers/new.html.erb
<h1>New Worker</h1>

<%= render 'form', worker: @worker %>

<%= link_to 'Back', workers_path,class: 'btn-back' %>

app/views/workers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @worker.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @worker.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @worker.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @worker.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @worker.zip %>
</p>

<p>
  <strong>Payrate:</strong>
  <%= @worker.payrate %>
</p>

<%= link_to 'Edit', edit_worker_path(@worker),class: 'btn-back' %> |
<%= link_to 'Back', workers_path ,class: 'btn-back'%>

app/views/workers/show.js.erb
$("#worker_content").html("<%= escape_javascript(render partial: 'workers/show1', locals: { worker: @worker } ) %>");