config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :vendors
  resources :docks
  resources :workers

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'welcome/home', to: 'welcome#home'
  get 'welcome/manual', to: 'welcome#manual'
  get 'welcome/post_mortem', to: 'welcome#post_mortem'
  get 'welcome/requirements', to: 'welcome#requirements'
  get 'welcome/design_documentation', to: 'welcome#design_documentation'
  get 'welcome/docs_main', to: 'welcome#docs_main'
  get 'welcome/report', to: 'welcome#report'
  post 'welcome/report', to: 'welcome#report'
  get 'welcome/dockreport', to: 'welcome#dockreport'


end

app/models/dock.rb
class Dock < ApplicationRecord


  has_many :workers, :through => :appointments
  has_many :appointments

  validates :name, presence: true
  validates :name, uniqueness: true

end

app/controllers/docks_controller.rb
class DocksController < ApplicationController
  before_action :set_dock, only: [:show, :edit, :update, :destroy]

  # GET /docks
  # GET /docks.json
  def index

    @docks = Dock.where(:archive => false)
  end

  # GET /docks/1
  # GET /docks/1.json
  def show
  end

  # GET /docks/new
  def new
    @dock = Dock.new
  end

  # GET /docks/1/edit
  def edit
  end

  # POST /docks
  # POST /docks.json
  def create
    @dock = Dock.new(dock_params)

    respond_to do |format|
      if @dock.save
        format.html { redirect_to @dock, notice: 'Dock was successfully created.' }
        format.json { render :show, status: :created, location: @dock }
      else
        format.html { render :new }
        format.json { render json: @dock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /docks/1
  # PATCH/PUT /docks/1.json
  def update
    respond_to do |format|
      if @dock.update(dock_params)
        format.html { redirect_to @dock, notice: 'Dock was successfully updated.' }
        format.json { render :show, status: :ok, location: @dock }
      else
        format.html { render :edit }
        format.json { render json: @dock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /docks/1
  # DELETE /docks/1.json
  def destroy
    #@dock.destroy

    @dock = Dock.find(params[:id])
    @dock.update_attribute(:archive,  true)

    respond_to do |format|
      format.html { redirect_to docks_url, notice: 'Dock was successfully archived.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dock
      @dock = Dock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dock_params
      params.require(:dock).permit(:name, :available)
    end
end

app/helpers/docks_helper.rb
module DocksHelper
end

app/views/docks/_form.html.erb
<%= form_for(dock) do |f| %>
  <% if dock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(dock.errors.count, "error") %> -- Khhhaaaaaaannn!  Dock not saved!</h2>

      <ul>
      <% dock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label 'Active' %>
    <%= f.check_box :available %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/docks/edit.html.erb
<h1>Editing Dock</h1>

<%= render 'form', dock: @dock %>


<%= link_to 'Back', docks_path,class: 'btn-back' %>

app/views/docks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Docks</h1>
<%= link_to 'New Dock', new_dock_path, class: "new_btn" %>
<br>
<br>
<br>

<table>
  <thead>
  <col width="200">
  <tr>
    <th >Name</th>
    <th>Active</th>

  </tr>
  </thead>
</table>



<div id="scroll">
 <table>

  <tbody>
    <% @docks.each do |dock| %>

      <tr>
        <td col width="200"><%= dock.name %></td>
        <td col width="250"><%= dock.available %></td>

        <td col width="35"><%= link_to 'Edit', edit_dock_path(dock), class: 'btn-index' %></td>
        <td ><%= link_to 'Archive', dock, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn-index' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</div>

app/views/docks/new.html.erb
<h1>New Dock</h1>

<%= render 'form', dock: @dock %>

<%= link_to 'Back', docks_path,class: 'btn-back' %>

app/views/docks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @dock.name %>
</p>

<p>
  <strong>Active:</strong>
  <%= @dock.available %>
</p>

<%= link_to 'Edit', edit_dock_path(@dock),class: 'btn-back' %> |
<%= link_to 'Back', docks_path,class: 'btn-back' %>