config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :vendors
  resources :docks
  resources :workers

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'welcome/home', to: 'welcome#home'
  get 'welcome/manual', to: 'welcome#manual'
  get 'welcome/post_mortem', to: 'welcome#post_mortem'
  get 'welcome/requirements', to: 'welcome#requirements'
  get 'welcome/design_documentation', to: 'welcome#design_documentation'
  get 'welcome/docs_main', to: 'welcome#docs_main'
  get 'welcome/report', to: 'welcome#report'
  post 'welcome/report', to: 'welcome#report'
  get 'welcome/dockreport', to: 'welcome#dockreport'


end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "CIS4339 Project" , welcome_home_path, class:"navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">

      <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style="color: white">Go To <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Appointments" , appointments_path %></li>
            <li><%= link_to "Docks" , docks_path %></li>
            <li><%= link_to "Dock Workers" , workers_path %></li>
            <li><%= link_to "Vendors" , vendors_path %></li>
            

          </ul>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">


        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style="color: white">Reports <span class="caret"></span></a>
          <ul class="dropdown-menu">

            <li><%= link_to "Dock worker report" , welcome_report_path %></li>
            <li><%= link_to "Dock Usage Report" , welcome_dockreport_path %></li>

          </ul>
        </li>




        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style="color: white">Documentation <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Documentation Overview" , welcome_docs_main_path %></li>
            <li role="separator" class="divider"></li>
            <li ><%= link_to "Manual" , welcome_manual_path %></li>
            <li><%= link_to "Design Documentation" , welcome_design_documentation_path %></li>
            <li><%= link_to "Requirements" , welcome_requirements_path %></li>

            <li><%= link_to "Post-Mortem" , welcome_post_mortem_path %></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SemProjCis4339</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/navigation'%>






  <%= yield %>
  </body>
</html>